version: '3.3'
services:
  db:
    build: ./
    command: 
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 3306:3306
    env_file:
      - mysql.env
